<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://reponseWSAppelSkyblue.skyblue.alacom.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://reponseWSAppelSkyblue.skyblue.alacom.com/" name="SkyBlueWebServiceService">
<types>
<xsd:schema>
<xsd:import namespace="http://reponseWSAppelSkyblue.skyblue.alacom.com/" schemaLocation="../xsd/ServeurLWS.xsd"></xsd:import>
</xsd:schema>
</types>
<message name="Requete">
<part name="parameters" element="tns:Requete"></part>
</message>
<message name="RequeteResponse">
<part name="parameters" element="tns:RequeteResponse"></part>
</message>
<message name="JAXBException">
<part name="fault" element="tns:JAXBException"></part>
</message>
<portType name="SkyBlueWS">
<operation name="Requete">
<input message="tns:Requete"></input>
<output message="tns:RequeteResponse"></output>
<fault message="tns:JAXBException" name="JAXBException"></fault>
</operation>
</portType>
<binding name="SkyBlueWSPortBinding" type="tns:SkyBlueWS">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"></soap:binding>
<operation name="Requete">
<soap:operation soapAction=""></soap:operation>
<input>
<soap:body use="literal"></soap:body>
</input>
<output>
<soap:body use="literal"></soap:body>
</output>
<fault name="JAXBException">
<soap:fault name="JAXBException" use="literal"></soap:fault>
</fault>
</operation>
</binding>
<service name="SkyBlueWebServiceService">
<port name="SkyBlueWSPort" binding="tns:SkyBlueWSPortBinding">
<soap:address location="http://localhost:8080/WebService_430/ServeurLWS"></soap:address>
</port>
</service>
</definitions>
